package dev.openrune.cache.tools.cs2

import com.google.gson.GsonBuilder
import com.google.gson.JsonParser
import net.lingala.zip4j.ZipFile
import net.lingala.zip4j.model.ZipParameters
import net.lingala.zip4j.model.enums.CompressionLevel
import java.io.File
import java.net.HttpURLConnection
import java.net.URL
import java.util.concurrent.Callable
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.Executors
import java.time.LocalDate

/**
 * Builds a Neptune-style CS2 project directory for every OSRS revision / sub revision found
 * by [OsrsDumpsRevisionIndex], laid out the same way as the bundled zips under
 * `packcs2/install/`:
 *
 * ```
 * <output>/<rev>.<subRev>/
 *   script/            every decompiled script from Joshua-F/osrs-dumps at that commit
 *   symbols/           the hand-maintained symbol files (see [SYMBOL_FILES]); the cache-derived
 *                      tables (obj, npc, loc, ...) are regenerated by SymDumper at pack time
 *   symbols/commands.sym  opcode -> name, generated for the revision by [ZwyzCommandTable]
 *   .prelude/          command signatures generated for the revision by [ZwyzCommandTable] from
 *                      zwyz/osrs-cache (the decompiler's own tables), plus builtin.cs2 from
 *                      neptune-ps/clientscript for the compiler-side commands
 *   bundle.json        provenance: commit shas, OpenRS2 cache id
 * ```
 */
class Cs2PackageBuilder(
    private val outputRoot: File,
    private val minRevision: Int = DEFAULT_MIN_REVISION,
    private val force: Boolean = false,
    /**
     * Commit or branch of zwyz/osrs-cache to take command tables from.
     *
     * `master` is the right default: Joshua-F regenerates every historical dump with the latest
     * decompiler, so old scripts use today's command names (e.g. 230.2 scripts call
     * `stockmarket_value`, which zwyz only named after rev 233), and the per-revision signature
     * differences are already encoded in the files via their trailing revision markers.
     *
     * `null` instead picks a commit per revision: the one right before zwyz's "update to <next rev>"
     * commit. That freezes the table as it stood while the revision was current, but leaves newer
     * names undeclared; only use it with dumps produced at the time.
     */
    private val zwyzRef: String? = "master",
    /**
     * Copy every `symbols/` file from the dump instead of only [SYMBOL_FILES]. Useful for
     * compiling a package standalone; the cache-derived tables are normally regenerated by
     * SymDumper at pack time and should not ship in the bundle.
     */
    private val allSymbols: Boolean = false,
    /**
     * Directory of bundles that already exist, normally `tools/src/main/resources/packcs2/install`.
     * Sub revisions that already have a `<rev>.<sub>.zip` there are left out, so a run only produces
     * what is missing.
     */
    private val existingBundleDir: File? = null,
    /**
     * Write each package as `<rev>.<sub>.zip` in the install bundle layout rather than leaving a
     * directory behind. A shipped bundle never carries the cache-derived symbol tables, so this
     * forces [allSymbols] off; SymDumper regenerates those at pack time.
     */
    private val zipOutput: Boolean = false,
    private val parallelism: Int = 1,
) {
    data class BuiltPackage(
        val entry: OsrsDumpsRevisionIndex.DumpRevision,
        val directory: File,
        val skipped: Boolean,
        val unchanged: Boolean = false,
    )

    private data class PreludeCommit(val sha: String, val timestamp: String, val message: String) {
        val date: LocalDate get() = LocalDate.parse(timestamp.take(10))
    }

    /** A shipped bundle must not contain cache-derived symbols; SymDumper writes those at pack time. */
    private val effectiveAllSymbols = allSymbols && !zipOutput

    private fun existingBundle(label: String): File? =
        existingBundleDir?.resolve("$label.zip")?.takeIf { it.exists() }

    private val gson = GsonBuilder().setPrettyPrinting().create()
    private val preludeCommits: List<PreludeCommit> by lazy { fetchPreludeCommits() }
    private val zwyzTables = ConcurrentHashMap<String, ZwyzCommandTable>()
    private val resolvedTables = ConcurrentHashMap<Int, ZwyzCommandTable.Resolved>()

    /** zwyz commits, oldest first, with the revision each "update to N" style message introduces. */
    private data class ZwyzCommit(val sha: String, val parentSha: String?, val message: String, val introducesRev: Int?)
    private val zwyzCommits: List<ZwyzCommit> by lazy { fetchZwyzCommits() }

    private fun tableFor(ref: String): ZwyzCommandTable = zwyzTables.computeIfAbsent(ref) { ZwyzCommandTable.fetch(it) }

    private fun tableForRevision(rev: Int): ZwyzCommandTable.Resolved =
        resolvedTables.computeIfAbsent(rev) { computeTableForRevision(it) }

    /**
     * Command table for [rev]: the chosen commit, plus the names that commit's revision-era table
     * used as aliases. Dumps are generated by whatever decompiler was current when Joshua-F ran it,
     * so a revision can use either spelling of a renamed command.
     */
    private fun computeTableForRevision(rev: Int): ZwyzCommandTable.Resolved {
        val primaryRef = zwyzRef ?: zwyzRefFor(rev)
        var table = tableFor(primaryRef).resolve(rev)
        // A dump carries whatever command names its decompiler had, and its commit date is the game
        // update date rather than the date it was generated, so it does not say which version that was.
        // Folding in every revision-era table means either spelling of a renamed command resolves.
        for (ref in historicalRefs()) {
            if (ref == primaryRef) continue
            table = table.withAliases(tableFor(ref).resolve(rev))
        }
        return table
    }

    /** Parent commit of every zwyz "update to N" commit, newest first: the table as each revision ended. */
    private fun historicalRefs(): List<String> =
        zwyzCommits.asReversed().filter { it.introducesRev != null }.mapNotNull { it.parentSha }.distinct()

    /** The commit right before the first zwyz commit that introduces a revision above [rev], else `master`. */
    private fun zwyzRefFor(rev: Int): String {
        val next = zwyzCommits.firstOrNull { it.introducesRev != null && it.introducesRev > rev } ?: return "master"
        return next.parentSha ?: "master"
    }

    private fun fetchZwyzCommits(): List<ZwyzCommit> {
        val commits = mutableListOf<ZwyzCommit>()
        var page = 1
        while (true) {
            val body = GitHub.get("https://api.github.com/repos/${ZwyzCommandTable.REPO}/commits?per_page=100&page=$page")
            val array = JsonParser.parseString(body).asJsonArray
            if (array.isEmpty) break
            for (element in array) {
                val obj = element.asJsonObject
                val message = obj.getAsJsonObject("commit")["message"].asString.lineSequence().first().trim()
                commits += ZwyzCommit(
                    sha = obj["sha"].asString,
                    parentSha = obj.getAsJsonArray("parents").firstOrNull()?.asJsonObject?.get("sha")?.asString,
                    message = message,
                    introducesRev = ZWYZ_UPDATE_MESSAGE.matchEntire(message)?.groupValues?.get(1)?.toInt(),
                )
            }
            if (array.size() < 100) break
            page++
        }
        return commits.asReversed()
    }

    fun buildAll(filter: (OsrsDumpsRevisionIndex.DumpRevision) -> Boolean = { true }): List<BuiltPackage> {
        val entries = OsrsDumpsRevisionIndex.generate()
            .filter { it.rev >= minRevision && it.subRev > 0 }
            .filter(filter)
            .sortedWith(compareBy({ it.rev }, { it.subRev }))
        val (present, wanted) = entries.partition { existingBundle(it.label) != null }
        if (present.isNotEmpty()) {
            println("${present.size} sub revs already bundled in ${existingBundleDir?.absolutePath}: ${present.joinToString(" ") { it.label }}")
        }
        println("Building ${wanted.size} packages into ${outputRoot.absolutePath}")
        if (wanted.isEmpty()) return emptyList()

        // Resolve the shared work before fanning out: the commit lists and the per-revision command
        // tables cost a series of downloads each and are identical for every package.
        preludeCommits
        wanted.map { it.rev }.distinct().forEach { tableForRevision(it) }

        if (parallelism <= 1) {
            return wanted.map { build(it) }.also { if (zipOutput) sweepStagingDirs() }
        }

        println("using $parallelism parallel workers")
        val pool = Executors.newFixedThreadPool(parallelism)
        return try {
            pool.invokeAll(wanted.map { entry -> Callable { build(entry) } }).map { it.get() }
                .also { if (zipOutput) sweepStagingDirs() }
        } finally {
            pool.shutdown()
        }
    }

    fun build(entry: OsrsDumpsRevisionIndex.DumpRevision): BuiltPackage {
        val dir = File(outputRoot, entry.label)
        val marker = File(dir, BUNDLE_FILE)
        val zipFile = File(outputRoot, "${entry.label}.zip")
        if (zipOutput && zipFile.exists() && !force) {
            println("${entry.label}: ${zipFile.name} already built, skipping")
            return BuiltPackage(entry, dir, skipped = true)
        }
        // In zip mode the zip is the artifact, so a leftover directory never counts as done.
        if (!zipOutput && marker.exists() && !force) {
            val preludeDir = File(dir, ".prelude")
            val missing = HANDWRITTEN_PRELUDE.filter { !File(preludeDir, it).exists() }
            if (missing.isNotEmpty()) {
                println("${entry.label}: already built, adding missing ${missing.joinToString()}")
                extractPreludeFiles(preludeCommits.last(), preludeDir) { it in missing }
            } else {
                println("${entry.label}: already built, skipping")
            }
            return BuiltPackage(entry, dir, skipped = true)
        }
        if (!force && !hasScriptChanges(entry)) {
            println("${entry.label}: commit ${entry.commitSha.take(8)} changed no scripts or symbols, no package needed")
            if (dir.exists()) dir.deleteRecursively()
            return BuiltPackage(entry, dir, skipped = true, unchanged = true)
        }

        if (dir.exists()) dir.deleteRecursively()
        dir.mkdirs()

        println("${entry.label}: dump ${entry.commitSha.take(8)} (${entry.date}${entry.suffix})")
        extractDump(entry, dir)

        val table = tableForRevision(entry.rev)
        val aliasCount = table.aliases.values.sumOf { it.size }
        println(
            "${entry.label}: ${table.commands.size} commands from zwyz/osrs-cache@${table.commitSha.take(8)}" +
                " resolved for rev ${entry.rev}" + if (aliasCount > 0) " (+$aliasCount historical aliases)" else ""
        )
        table.writeCommandsSym(File(dir, "symbols/commands.sym"))
        val preludeDir = File(dir, ".prelude")
        table.writePrelude(preludeDir)

        // builtin.cs2 (script, dump) and hook.cs2 (event_*) document compiler-side commands; they are
        // hand-written in the neptune-ps prelude repo and have no zwyz equivalent, so take the newest copies.
        val builtinCommit = preludeCommits.last()
        extractPreludeFiles(builtinCommit, preludeDir) { it in HANDWRITTEN_PRELUDE }

        marker.writeText(
            gson.toJson(
                mapOf(
                    "rev" to entry.rev,
                    "subRev" to entry.subRev,
                    "date" to entry.date.toString() + entry.suffix,
                    "dumpRepo" to OsrsDumpsRevisionIndex.REPO,
                    "dumpCommit" to entry.commitSha,
                    "dumpUrl" to entry.treeUrl,
                    "openRs2CacheId" to entry.openRs2CacheId,
                    "openRs2Url" to entry.openRs2Url,
                    "allSymbols" to effectiveAllSymbols,
                    "commandsRepo" to ZwyzCommandTable.REPO,
                    "commandsCommit" to table.commitSha,
                    "builtinPreludeRepo" to PRELUDE_REPO,
                    "builtinPreludeCommit" to builtinCommit.sha,
                )
            )
        )
        if (zipOutput) {
            writeBundleZip(dir, zipFile)
            removeStagingDir(dir)
            println("${entry.label}: wrote ${zipFile.name} (${zipFile.length() / 1024} KiB)")
        }
        return BuiltPackage(entry, dir, skipped = false)
    }

    /**
     * Drops the staging directory once its zip exists, so only bundles are left behind. Windows can
     * still hold a handle on a file that was just closed, and a package is several thousand files,
     * so a single delete can half-succeed; retry before giving up and saying so.
     */
    private fun removeStagingDir(dir: File) {
        repeat(3) { attempt ->
            if (!dir.exists() || dir.deleteRecursively()) return
            Thread.sleep(250L * (attempt + 1))
        }
        if (dir.exists()) {
            println("warning: ${dir.name} could not be removed; delete it before packaging")
        }
    }

    /** Catches any staging directory whose zip exists but whose delete lost a race. */
    private fun sweepStagingDirs() {
        outputRoot.listFiles().orEmpty()
            .filter { it.isDirectory && File(outputRoot, "${it.name}.zip").exists() }
            .forEach { removeStagingDir(it) }
    }

    /**
     * Zips the package with `script/`, `symbols/` and `.prelude/` at the archive root, which is the
     * layout `Cs2BundleExtract` expects of an install bundle.
     */
    private fun writeBundleZip(dir: File, target: File) {
        target.delete()
        val parameters = ZipParameters().apply { compressionLevel = CompressionLevel.MAXIMUM }
        ZipFile(target).use { zip ->
            for (child in dir.listFiles().orEmpty().sortedBy { it.name }) {
                if (child.isDirectory) zip.addFolder(child, parameters) else zip.addFile(child, parameters)
            }
        }
    }

    private fun extractDump(entry: OsrsDumpsRevisionIndex.DumpRevision, dir: File) {
        withArchive(OsrsDumpsRevisionIndex.REPO, entry.commitSha) { zip, rootPrefix ->
            var scripts = 0
            for (header in zip.fileHeaders) {
                if (header.isDirectory) continue
                val path = header.fileName.removePrefix(rootPrefix)
                val target = when {
                    path.startsWith("script/") -> path
                    path.startsWith("symbols/") && isWantedSymbol(path.removePrefix("symbols/")) -> path
                    else -> continue
                }
                val file = File(dir, target)
                if (target.startsWith("script/")) {
                    scripts++
                    if (LegacyArraySyntax.applies(entry.rev)) {
                        file.parentFile.mkdirs()
                        val source = zip.getInputStream(header).bufferedReader().use { it.readText() }
                        file.writeText(LegacyArraySyntax.rewrite(source))
                        continue
                    }
                }
                extractTo(zip, header, file)
            }
            println("${entry.label}: $scripts scripts" + if (LegacyArraySyntax.applies(entry.rev)) " (legacy array syntax rewritten)" else "")
        }
    }

    private fun isWantedSymbol(relative: String): Boolean =
        effectiveAllSymbols || relative.startsWith("constant/") || relative in SYMBOL_FILES

    private fun hasScriptChanges(entry: OsrsDumpsRevisionIndex.DumpRevision): Boolean {
        val parent = entry.parentSha ?: return true
        return packagedObjectShas(entry.commitSha) != packagedObjectShas(parent)
    }

    private fun packagedObjectShas(commitSha: String): Map<String, String> {
        val root = tree("${OsrsDumpsRevisionIndex.REPO}/git/trees/$commitSha")
        val result = mutableMapOf<String, String>()
        root["script"]?.let { result["script"] = it }
        if (root.containsKey("symbols")) {
            val symbols = tree("${OsrsDumpsRevisionIndex.REPO}/git/trees/$commitSha:symbols")
            for ((name, sha) in symbols) {
                if (name == "constant" || name in SYMBOL_FILES) result["symbols/$name"] = sha
            }
        }
        return result
    }

    /** Entry name -> object sha for one level of a git tree. */
    private fun tree(path: String): Map<String, String> {
        val body = OsrsDumpsRevisionIndex.get("https://api.github.com/repos/$path")
        return JsonParser.parseString(body).asJsonObject.getAsJsonArray("tree")
            .associate { it.asJsonObject["path"].asString to it.asJsonObject["sha"].asString }
    }

    // -- prelude -----------------------------------------------------------------------------

    private fun extractPreludeFiles(commit: PreludeCommit, preludeDir: File, wanted: (String) -> Boolean) {
        withArchive(PRELUDE_REPO, commit.sha) { zip, rootPrefix ->
            for (header in zip.fileHeaders) {
                if (header.isDirectory) continue
                val path = header.fileName.removePrefix(rootPrefix)
                // prelude files sit at the repository root; ignore nested dirs and dotfiles
                if (path.contains('/') || !path.endsWith(".cs2") || !wanted(path)) continue
                extractTo(zip, header, File(preludeDir, path))
            }
        }
    }

    /** Oldest first. */
    private fun fetchPreludeCommits(): List<PreludeCommit> {
        val commits = mutableListOf<PreludeCommit>()
        var page = 1
        while (true) {
            val body = GitHub.get("https://api.github.com/repos/$PRELUDE_REPO/commits?per_page=100&page=$page")
            val array = JsonParser.parseString(body).asJsonArray
            if (array.isEmpty) break
            for (element in array) {
                val obj = element.asJsonObject
                val commit = obj.getAsJsonObject("commit")
                commits += PreludeCommit(
                    sha = obj["sha"].asString,
                    timestamp = commit.getAsJsonObject("committer")["date"].asString,
                    message = commit["message"].asString.lineSequence().first(),
                )
            }
            if (array.size() < 100) break
            page++
        }
        check(commits.isNotEmpty()) { "No commits found in $PRELUDE_REPO" }
        // ISO-8601 UTC timestamps sort lexically; several commits can share one date.
        return commits.sortedBy { it.timestamp }
    }

    // -- helpers -----------------------------------------------------------------------------

    /** Downloads the GitHub source archive for [sha] and hands the opened zip plus its root folder prefix to [block]. */
    private fun withArchive(repo: String, sha: String, block: (ZipFile, String) -> Unit) {
        val temp = File.createTempFile("openrune-${repo.substringAfter('/')}-", ".zip")
        try {
            GitHub.download("https://codeload.github.com/$repo/zip/$sha", temp)
            ZipFile(temp).use { zip ->
                val rootPrefix = zip.fileHeaders.first().fileName.substringBefore('/') + "/"
                block(zip, rootPrefix)
            }
        } finally {
            temp.delete()
        }
    }

    private fun extractTo(zip: ZipFile, header: net.lingala.zip4j.model.FileHeader, target: File) {
        target.parentFile.mkdirs()
        zip.getInputStream(header).use { input -> target.outputStream().use { input.copyTo(it) } }
    }

    private object GitHub {
        fun get(url: String): String = open(url).use { it.inputStream.bufferedReader().readText() }

        fun download(url: String, destination: File) {
            open(url).use { connection ->
                connection.inputStream.use { input -> destination.outputStream().use { input.copyTo(it) } }
            }
        }

        private fun open(url: String): AutoCloseableConnection {
            val connection = (URL(url).openConnection() as HttpURLConnection).apply {
                requestMethod = "GET"
                connectTimeout = 15_000
                readTimeout = 120_000
                instanceFollowRedirects = true
                setRequestProperty("User-Agent", "OpenRune-FileStore")
                if (url.startsWith("https://api.github.com/")) {
                    setRequestProperty("Accept", "application/vnd.github+json")
                    OsrsDumpsRevisionIndex.githubToken?.let { setRequestProperty("Authorization", "Bearer $it") }
                }
            }
            if (connection.responseCode != 200) {
                val error = connection.errorStream?.bufferedReader()?.readText().orEmpty()
                connection.disconnect()
                error("GitHub request failed (${connection.responseCode}) for $url: $error")
            }
            return AutoCloseableConnection(connection)
        }

        class AutoCloseableConnection(private val connection: HttpURLConnection) : AutoCloseable {
            val inputStream get() = connection.inputStream
            override fun close() = connection.disconnect()
        }
    }

    companion object {
        const val PRELUDE_REPO = "neptune-ps/clientscript"
        const val BUNDLE_FILE = "bundle.json"

        /** Oldest revision packages are built for by default. */
        const val DEFAULT_MIN_REVISION = 230
        /** zwyz commit messages that switch the tables to a new revision: "update to 240", "update to 232.2", "231". */
        private val ZWYZ_UPDATE_MESSAGE = Regex("""(?i)^(?:update to )?(\d{3})(?:\.\d+)?$""")

        /** Prelude files taken from neptune-ps/clientscript because they describe compiler builtins, not client opcodes. */
        val HANDWRITTEN_PRELUDE = setOf("builtin.cs2", "hook.cs2")

        /** Symbol tables that are not regenerated from the cache by SymDumper, mirroring the bundled install zips. */
        val SYMBOL_FILES = setOf(
            "clientscript.sym",
            "if_script.sym",
            "locshape.sym",
            "midi.sym",
            "varc.sym",
            "varp.sym",
        )

        /**
         * Usage: `<outputDir> [minRev] [only]` where `only` is `rev` or `rev.sub`, e.g. `238` or `238.2`.
         * Set `-Dforce=true` to rebuild existing packages, `-DallSymbols=true` to include every
         * symbol file from the dump (standalone testing only) and `-DzwyzRef=<sha|branch|beforeNext>`
         * to choose the zwyz command table commit.
         *
         * For install resources: `-DzipOutput=true` writes each package as a bundle zip with no
         * cache-derived symbols, and `-DexistingBundles=<dir>` skips the sub revisions already there.
         */
        @JvmStatic
        fun main(args: Array<String>) {
            require(args.isNotEmpty()) { "Usage: Cs2PackageBuilder <outputDir> [minRev] [only]" }
            val output = File(args[0])
            val minRev = args.getOrNull(1)?.toIntOrNull() ?: DEFAULT_MIN_REVISION
            val only = args.getOrNull(2)
            val force = System.getProperty("force")?.toBoolean() ?: false
            val allSymbols = System.getProperty("allSymbols")?.toBoolean() ?: false
            // -DzwyzRef=<sha|branch>, or "beforeNext" for the per-revision commit picker
            val zwyzRef = System.getProperty("zwyzRef")?.let { if (it == "beforeNext") null else it } ?: "master"

            val filter: (OsrsDumpsRevisionIndex.DumpRevision) -> Boolean = when {
                only == null -> { _ -> true }
                // accepts a comma separated mix of whole revisions and labels, e.g. "238,239.1"
                else -> {
                    val wanted = only.split(',').map { it.trim() }.filter { it.isNotEmpty() }.toSet()
                    val byLabelOrRev: (OsrsDumpsRevisionIndex.DumpRevision) -> Boolean =
                        { e -> e.label in wanted || e.rev.toString() in wanted }
                    byLabelOrRev
                }
            }

            val zipOutput = System.getProperty("zipOutput")?.toBoolean() ?: false
            val existingBundles = System.getProperty("existingBundles")?.takeIf { it.isNotBlank() }?.let(::File)
            val parallel = System.getProperty("parallel")?.toIntOrNull()?.coerceAtLeast(1) ?: 1

            val built = Cs2PackageBuilder(
                output,
                minRev,
                force,
                zwyzRef = zwyzRef,
                allSymbols = allSymbols,
                existingBundleDir = existingBundles,
                zipOutput = zipOutput,
                parallelism = parallel,
            ).buildAll(filter)
            val fresh = built.count { !it.skipped }
            val unchanged = built.count { it.unchanged }
            println("Done: ${built.size} sub revs ($fresh built, ${built.size - fresh - unchanged} already present, $unchanged without script changes)")
        }
    }
}
