package dev.openrune.definition.type.widget

@DslMarker private annotation class ComponentBuilderDsl

@ComponentBuilderDsl
class ComponentTypeBuilder(var internal: String? = null) {
    var v3: Boolean? = null
    var type: Int? = null
    var buttonType: Int? = null
    var contentType: Int? = null
    var x: Int? = null
    var y: Int? = null
    var width: Int? = null
    var height: Int? = null
    var trans1: Int? = null
    var layer: Int? = null
    var mouseOverRedirect: Int? = null
    var cs1Comparisons: ShortArray? = null
    var cs1ComparisonValues: IntArray? = null
    var cs1Instructions: Array<IntArray>? = null
    var scrollHeight: Int? = null
    var hide: Boolean? = null
    var fill: Boolean? = null
    var textAlignH: Int? = null
    var textAlignV: Int? = null
    var textLineHeight: Int? = null
    var textFont: Int? = null
    var textShadow: Boolean? = null
    var secondaryText: String? = null
    var colour1: Int? = null
    var colour2: Int? = null
    var mouseOverColour1: Int? = null
    var mouseOverColour2: Int? = null
    var graphic: Int? = null
    var secondaryGraphic: Int? = null
    var modelKind: Int? = null
    var model: Int? = null
    var secondaryModelKind: Int? = null
    var secondaryModel: Int? = null
    var modelAnim: Int? = null
    var secondaryModelAnim: Int? = null
    var modelZoom: Int? = null
    var modelAngleX: Int? = null
    var modelAngleY: Int? = null
    var text: String? = null
    var targetVerb: String? = null
    var targetBase: String? = null
    var events: Int? = null
    var buttonText: String? = null
    var widthMode: Int? = null
    var heightMode: Int? = null
    var xMode: Int? = null
    var yMode: Int? = null
    var scrollWidth: Int? = null
    var noClickThrough: Boolean? = null
    var angle2d: Int? = null
    var tiling: Boolean? = null
    var outline: Int? = null
    var graphicShadow: Int? = null
    var vFlip: Boolean? = null
    var hFlip: Boolean? = null
    var modelX: Int? = null
    var modelY: Int? = null
    var modelAngleZ: Int? = null
    var modelOrthog: Boolean? = null
    var modelObjWidth: Int? = null
    var lineWid: Int? = null
    var lineDirection: Boolean? = null
    var opBase: String? = null
    var op: Array<String> = arrayOf()
    var dragDeadZone: Int? = null
    var dragDeadTime: Int? = null
    var draggableBehavior: Boolean? = null
    var onLoad: Array<Any>? = null
    var onMouseOver: Array<Any>? = null
    var onMouseLeave: Array<Any>? = null
    var onTargetLeave: Array<Any>? = null
    var onTargetEnter: Array<Any>? = null
    var onVarTransmit: Array<Any>? = null
    var onInvTransmit: Array<Any>? = null
    var onStatTransmit: Array<Any>? = null
    var onTimer: Array<Any>? = null
    var onOp: Array<Any>? = null
    var onMouseRepeat: Array<Any>? = null
    var onClick: Array<Any>? = null
    var onClickRepeat: Array<Any>? = null
    var onRelease: Array<Any>? = null
    var onHold: Array<Any>? = null
    var onDrag: Array<Any>? = null
    var onDragComplete: Array<Any>? = null
    var onScrollWheel: Array<Any>? = null
    var onVarTransmitList: IntArray? = null
    var onInvTransmitList: IntArray? = null
    var onStatTransmitList: IntArray? = null

    fun build(id: Int): ComponentType {
        val internal = checkNotNull(internal) { "`internal` must be set." }
        val v3 = checkNotNull(v3) { "`v3` must be set." }
        val type = type ?: 0
        val buttonType = buttonType ?: 0
        val contentType = contentType ?: 0
        val x = x ?: 0
        val y = y ?: 0
        val width = width ?: 0
        val height = height ?: 0
        val trans1 = trans1 ?: 0
        val layer = layer ?: DEFAULT_LAYER
        val mouseOverRedirect = mouseOverRedirect ?: DEFAULT_MOUSE_OVER_REDIRECT
        val scrollHeight = scrollHeight ?: 0
        val hide = hide == true
        val fill = fill == true
        val textAlignH = textAlignH ?: 0
        val textAlignV = textAlignV ?: 0
        val textLineHeight = textLineHeight ?: 0
        val textFont = textFont ?: DEFAULT_TEXT_FONT
        val textShadow = textShadow == true
        val secondaryText = secondaryText ?: DEFAULT_EMPTY_TEXT
        val colour1 = colour1 ?: 0
        val colour2 = colour2 ?: 0
        val mouseOverColour1 = mouseOverColour1 ?: 0
        val mouseOverColour2 = mouseOverColour2 ?: 0
        val graphic = graphic ?: DEFAULT_GRAPHIC
        val secondaryGraphic = secondaryGraphic ?: DEFAULT_SECONDARY_GRAPHIC
        val modelKind = modelKind ?: DEFAULT_MODEL_KIND
        val model = model ?: DEFAULT_MODEL
        val secondaryModelKind = secondaryModelKind ?: DEFAULT_SECONDARY_MODEL_KIND
        val secondaryModel = secondaryModel ?: DEFAULT_SECONDARY_MODEL
        val modelAnim = modelAnim ?: DEFAULT_MODEL_ANIM
        val secondaryModelAnim = secondaryModelAnim ?: DEFAULT_SECONDARY_MODEL_ANIM
        val modelZoom = modelZoom ?: DEFAULT_MODEL_ZOOM
        val modelAngleX = modelAngleX ?: 0
        val modelAngleY = modelAngleY ?: 0
        val text = text ?: DEFAULT_EMPTY_TEXT
        val targetVerb = targetVerb ?: DEFAULT_EMPTY_TEXT
        val targetBase = targetBase ?: DEFAULT_EMPTY_TEXT
        val events = events ?: 0
        val buttonText = buttonText ?: DEFAULT_BUTTON_TEXT
        val widthMode = widthMode ?: 0
        val heightMode = heightMode ?: 0
        val xMode = xMode ?: 0
        val yMode = yMode ?: 0
        val scrollWidth = scrollWidth ?: 0
        val noClickThrough = noClickThrough == true
        val angle2d = angle2d ?: 0
        val tiling = tiling == true
        val outline = outline ?: 0
        val graphicShadow = graphicShadow ?: 0
        val vFlip = vFlip == true
        val hFlip = hFlip == true
        val modelX = modelX ?: 0
        val modelY = modelY ?: 0
        val modelAngleZ = modelAngleZ ?: 0
        val modelOrthog = modelOrthog == true
        val modelObjWidth = modelObjWidth ?: 0
        val lineWid = lineWid ?: DEFAULT_LINE_WID
        val lineDirection = lineDirection == true
        val opBase = opBase ?: DEFAULT_EMPTY_TEXT
        val dragDeadZone = dragDeadZone ?: 0
        val dragDeadTime = dragDeadTime ?: 0
        val draggableBehavior = draggableBehavior == true
        return ComponentType(
            v3 = v3,
            type = type,
            buttonType = buttonType,
            clientCode = contentType,
            x = x,
            y = y,
            width = width,
            height = height,
            trans1 = trans1,
            layer = layer,
            mouseOverRedirect = mouseOverRedirect,
            cs1Comparisons = cs1Comparisons,
            cs1ComparisonValues = cs1ComparisonValues,
            cs1Instructions = cs1Instructions,
            scrollHeight = scrollHeight,
            hide = hide,
            fill = fill,
            textAlignH = textAlignH,
            textAlignV = textAlignV,
            textLineHeight = textLineHeight,
            textFont = textFont,
            textShadow = textShadow,
            secondaryText = secondaryText,
            colour1 = colour1,
            colour2 = colour2,
            mouseOverColour1 = mouseOverColour1,
            mouseOverColour2 = mouseOverColour2,
            graphic = graphic,
            secondaryGraphic = secondaryGraphic,
            modelKind = modelKind,
            model = model,
            secondaryModelKind = secondaryModelKind,
            secondaryModel = secondaryModel,
            modelAnim = modelAnim,
            secondaryModelAnim = secondaryModelAnim,
            modelZoom = modelZoom,
            modelAngleX = modelAngleX,
            modelAngleY = modelAngleY,
            text = text,
            targetVerb = targetVerb,
            targetBase = targetBase,
            events = events,
            buttonText = buttonText,
            widthMode = widthMode,
            heightMode = heightMode,
            xMode = xMode,
            yMode = yMode,
            scrollWidth = scrollWidth,
            noClickThrough = noClickThrough,
            angle2d = angle2d,
            tiling = tiling,
            outline = outline,
            graphicShadow = graphicShadow,
            vFlip = vFlip,
            hFlip = hFlip,
            modelX = modelX,
            modelY = modelY,
            modelAngleZ = modelAngleZ,
            modelOrthog = modelOrthog,
            modelObjWidth = modelObjWidth,
            lineWid = lineWid,
            lineDirection = lineDirection,
            opBase = opBase,
            op = op,
            dragDeadZone = dragDeadZone,
            dragDeadTime = dragDeadTime,
            draggableBehavior = draggableBehavior,
            onLoad = onLoad,
            onMouseOver = onMouseOver,
            onMouseLeave = onMouseLeave,
            onTargetLeave = onTargetLeave,
            onTargetEnter = onTargetEnter,
            onVarTransmit = onVarTransmit,
            onInvTransmit = onInvTransmit,
            onStatTransmit = onStatTransmit,
            onTimer = onTimer,
            onOp = onOp,
            onMouseRepeat = onMouseRepeat,
            onClick = onClick,
            onClickRepeat = onClickRepeat,
            onRelease = onRelease,
            onHold = onHold,
            onDrag = onDrag,
            onDragComplete = onDragComplete,
            onScrollWheel = onScrollWheel,
            onVarTransmitList = onVarTransmitList,
            onInvTransmitList = onInvTransmitList,
            onStatTransmitList = onStatTransmitList,
            internalId = id,
            internalName = internal,
        )
    }

    companion object {
        const val DEFAULT_LINE_WID: Int = 1
        const val DEFAULT_GRAPHIC: Int = -1
        const val DEFAULT_SECONDARY_GRAPHIC: Int = -1
        const val DEFAULT_MODEL_KIND: Int = 1
        const val DEFAULT_MODEL: Int = -1
        const val DEFAULT_SECONDARY_MODEL_KIND: Int = 1
        const val DEFAULT_SECONDARY_MODEL: Int = -1
        const val DEFAULT_MODEL_ANIM: Int = -1
        const val DEFAULT_SECONDARY_MODEL_ANIM: Int = -1
        const val DEFAULT_MODEL_ZOOM: Int = 100
        const val DEFAULT_TEXT_FONT: Int = -1
        const val DEFAULT_MOUSE_OVER_REDIRECT: Int = -1
        const val DEFAULT_BUTTON_TEXT: String = "Ok"
        const val DEFAULT_LAYER: Int = -1
        const val DEFAULT_EMPTY_TEXT: String = ""
    }
}
