package dev.openrune.rs2

import com.google.gson.Gson
import com.github.michaelbull.logging.InlineLogger

/** archives/configs: constant name -> earliest build it's known to exist by. xteaLastBuild: last build with any XTEA keys. Generated by `Rs2ManifestScanTest` into `src/main/resources/rs2-manifest.json`. */
data class Rs2ManifestData(
    val archives: Map<String, Int>,
    val configs: Map<String, Int>,
    val xteaLastBuild: Int? = null
)

/** Runtime lookup + best-effort warnings for [Rs2ManifestData]. Unknown names are silently skipped, not warned about. */
object Rs2Manifest {

    private val logger = InlineLogger()

    val data: Rs2ManifestData? by lazy { load() }

    private fun load(): Rs2ManifestData? {
        val stream = Rs2Manifest::class.java.classLoader.getResourceAsStream("rs2-manifest.json") ?: return null
        return stream.use { Gson().fromJson(it.reader(), Rs2ManifestData::class.java) }
    }

    fun archiveIntroducedBuild(archiveName: String): Int? = data?.archives?.get(archiveName)

    fun configIntroducedBuild(configName: String): Int? = data?.configs?.get(configName)

    fun warnIfArchiveTooEarly(archiveName: String, build: Int) {
        val introduced = archiveIntroducedBuild(archiveName) ?: return
        if (build < introduced) {
            logger.warn { "Archive $archiveName is not known to exist before build $introduced (requested for build $build)" }
        }
    }

    fun warnIfConfigTooEarly(configName: String, build: Int) {
        val introduced = configIntroducedBuild(configName) ?: return
        if (build < introduced) {
            logger.warn { "Config group $configName is not known to exist before build $introduced (requested for build $build)" }
        }
    }

    fun expectsXtea(build: Int): Boolean? = data?.xteaLastBuild?.let { build <= it }

    fun warnIfXteaMismatch(build: Int, hasKeys: Boolean) {
        val expected = expectsXtea(build) ?: return
        if (expected && !hasKeys) {
            logger.warn { "Build $build is expected to still use XTEA-encrypted maps (keys were used up to build ${data?.xteaLastBuild}), but no keys were supplied" }
        } else if (!expected && hasKeys) {
            logger.warn { "Build $build is expected to no longer use XTEA (keys were last used at build ${data?.xteaLastBuild}), but keys were supplied anyway" }
        }
    }

}
